### ISSUE TITLE
expose types from npm package

### ISSUE THREAD

**Issue by lemoustachiste** [blockchain-certificates/explorer-lookup#5]

**Comment by raiseandfall** [comment]
@lemoustachiste so it looks like we can either:
- generate and publish the declaration types directly in the pkg [using tsconfig](https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/). This would be automatic.
- publish our declaration types in MS @types, but I didn't find an automated way to do this

What would be the benefit of having our declaration types in a separate repo at this point?

**Comment by raiseandfall** [comment]
Closing, the types are inside the published package for now.
